export {default as LoginOld} from './Login/Login_old'
export {default as Profile} from './Profile/Profile'
export {default as Products} from './Products/Products'
export {default as Instalations} from './Instalations/Instalations'
export {default as Login } from './Login/Login'
export {default as InstalationForm } from './InstalationForm/InstalationForm'
export {default as NewLogin } from './NewLogin/NewLogin'